### ISSUE TITLE
Div doesn't resize to small amount of rows (see image)

### ISSUE THREAD

**Issue by ucg8j** [plotly/dash-table-experiments#25]
There is a lot of whitespace left if the rows displayed are less than ~10 rows. See the screenshot below. 

<img width="374" alt="div-gap" src="https://user-images.githubusercontent.com/6220504/33607000-5a8f9a6a-d9b7-11e7-88a5-5ade7551d400.png">

I'm posting this as an issue to seek any feedback prior to a PR.

**Comment by chriddyp** [comment]
Yeah, it would be great if this was fixed. I know that react-data-grid has a lot of constraints when it comes to sizing as it doesn't render all cells at once, only those in the viewport. 

I recommend looking through the react-data-grid repo for similar issues. For example, https://github.com/adazzle/react-data-grid/issues/207 and https://github.com/adazzle/react-data-grid/issues/736

Let me know if you need any help getting started!

**Comment by ucg8j** [comment]
See [PR27](https://github.com/plotly/dash-table-experiments/pull/27)

**Comment by chriddyp** [comment]
Fixed in #27
