### ISSUE TITLE
Ordering Columns

### ISSUE THREAD

**Issue by kylelt** [plotly/dash-table-experiments#3]
How do i specify the order of the columns to appear in the rendered output

**Comment by chrisbol** [comment]
+1, I assume the order of columns is getting mixed up because the data is converted to a dict

**Comment by chrisbol** [comment]
+1

**Comment by chriddyp** [comment]
Thanks for reporting! I just added a new `columns` property that allows you to specify the order: https://github.com/plotly/dash-table-experiments/commit/790173eed46ea0d28382491a73435d0fce5fa652

Upgrade with `pip install dash-table-experiments==0.2.1`
