### ISSUE TITLE
How to increase DataTables Height ? (To show more rows)

### ISSUE THREAD

**Issue by samholt** [plotly/dash-table-experiments#34]
Love your work so far, keep it up!

Would someone be able to help me, increase the visible rows on the screen at one time, such as in the example usage.py.

I've tried adding another kwarg of `min_height=1200` (to the DataTable object), however this has no effect of increasing the amount of rows visible (Height of the DataTable). Would you be so kind as to advise how to increase the height of a DataTable / to show more rows on the screen, with perhaps the necessary modifications to usage.py example to illustrate this ?

Thank you so much for your time,
Many thanks,

Sam

**Comment by samholt** [comment]
Also if one were to use a `dcc.interval`, to update the rows, of the DataTable (Live from another datasource, such as a request from somewhere else), this seems to reset the filtered rows, and sorted rows. Is there a way to persist this the filtered state / sorted state, to filter / sort the new rows in the same way ? Love your work, if you don't have enough time to implement, this, do point me in the right direction to modify, and I will fix these up, and submit a PR.

**Comment by engstromgustav** [comment]
The setting the min_height property as follows works for me:

    dt.DataTable(
        rows=DF_GAPMINDER.to_dict('records'),
        row_selectable=True,
        filterable=True,
        sortable=True,
        min_height=2000,
        selected_row_indices=[],
        id='datatable-gapminder'
    )

In order to dynamically adjust it based on a variable number of rows you can do this using a callback:

@app.callback(
    Output(component_id='data-table', component_property='min_height'),
    [Input(component_id='data-table', component_property='rows')]
)
def update_table_min_height(rows):
    return 35*(len(rows)+1)

**Comment by chriddyp** [comment]
Thanks @engstromgustav !

**Comment by ptim** [comment]
hmm... @engstromgustav 's solution is not working for me out of the box with v 0.5.4... will keep wiggling...

**Comment by andreabotti** [comment]
Hi @chriddyp, @engstromgustav solution does not work for me either. Any idea why this may be the case?

**Comment by gennadyi** [comment]
@andreabotti, @ptim  see this PR for latest update on this as far as I know: 
https://github.com/plotly/dash-table-experiments/pull/41
