### ISSUE TITLE
increasing display length

### ISSUE THREAD

**Issue by xiaoluffy** [plotly/dash-table-experiments#38]
Hi,

dash-table-experiments is great! But the default display rows of datatable is 9.   I found a way to work out by setting iDisplayLength of DataTable, but is there a simple way to work out by dash-table-experiments and Python code only?

And min_height does not work well as I expected.
app.layout = html.Div([
    html.H4('test1'),
    dt.DataTable(
        rows=df.to_dict('records'),
        columns=df.columns,
        row_selectable=True,
        filterable=True,
        min_height=2000,
        sortable=True,
        selected_row_indices=[],
        id='datatable-gapminder'
    ),
    html.Div(id='selected-indexes')
], className="container")

Thanks!

**Comment by chriddyp** [comment]
I believe that this was fixed in #37  which I released on v0.5.4. I'll close this for now, but feel free to reopen if this bug isn't fixed yet

**Comment by gennadyi** [comment]
Not fixed yet! Cant make table with more than 9 visible rows.
Infact min_height really has nothing to do with number of rows. Should be separate parameter.


only case for <10 works, 

10 should be a parameter called num_visible_rows !!
min_height is not enough 

==============================
    getMinHeight() {
-        if (this.getSize() < 10) {
-            return (this.getSize() * 35) + 35 + 15; // 35px extra edded for the filter box and 15px added for padding
+        if (typeof DataTable.defaultProps.min_height === 'undefined' && this.getSize() < 10) {
+            var filter_box_space = 0
+            if (this.props.filterable && this.getSize() < 2) {
+                filter_box_space = 45
+            }
+            return (this.getSize() * 35) + 35 + filter_box_space + 15;
         }
         return (typeof DataTable.defaultProps.min_height !== 'undefined') ? DataTable.defaultProps.min_height : 350;
     }

**Comment by gennadyi** [comment]
I can't reopen. But @xiaoluffy should reopen this issue.

**Comment by xiaoluffy** [comment]
hi,  I tried the same code today and it works by min_height.
thanks!
