### ISSUE TITLE
How to get the data of the selected rows?

### ISSUE THREAD

**Issue by aaron8tang** [plotly/dash-table-experiments#49]
For now, I use the selected_row_indices to get the corresponding rows of pandas dataframe, but after clicking the column head to sort data, using selected_row_indices can't get the corresponding rows of df. Is it possible to get the data of the selected rows, not just the indices?

Thanks.

**Comment by chriddyp** [comment]
Reposted and answered in https://community.plot.ly/t/how-to-get-the-data-of-the-selected-rows-of-dash-table-experiments/8439.
