### ISSUE TITLE
Scroll bar removal

### ISSUE THREAD

**Issue by Harlekuin** [plotly/dash-table-experiments#5]
I'm not sure if this has been done somewhere, or if it's related to "row_scroll_timeout", but it would be good if there a way to edit the height of the table or remove the vertical scroll bar in the table, i.e. have it span across x rows rather than a set amount or a set height

**Comment by chriddyp** [comment]
@Harlekuin  - did you end up finding a solution to this?

**Comment by Harlekuin** [comment]
@chriddyp I did - I simply leveraged the number of rows with the header_row_height and row_heights to set the min_height parameter (which causes the scroll bar to disappear). I thought this might not be an issue any more given it's pretty simple to get the exact height you're after using existing parameters.
