### ISSUE TITLE
Bundle.js - no such file or directory

### ISSUE THREAD

**Issue by vkrisha** [plotly/dash-table-experiments#51]
Hi,
i have cloned the repo and when i ran usage.py i go the below error and i didn't find bundle.js in dash_table_experiments/ so is it removed? or any otherway to fix this? if its an issue.

IOError: [Errno 2] No such file or directory: /dash-table-experiments/dash_table_experiments/bundle.js'

Thanks

**Comment by EvgeniiAl** [comment]
Hello, if you want only to try usage.py and don't need edit source files; then run:  
`$ pip install dash-table-experiments` . 
Otherwise, you have to build package itself:
 `$ npm run prepublish`
`$ python setup.py install`
